### ISSUE TITLE
overwrite ancient Module::Install?

### ISSUE THREAD

**Issue by miyagawa** [miyagawa/cpanminus#243]
Ancient version of Module::Install::AutoInstall has a code incompatible to perl 5.17+ and configure fails with the following.

```
Entering PerlIO-via-symlink-0.05
Checking configure dependencies from META.yml
Configuring PerlIO-via-symlink-0.05 ... Running Makefile.PL
Use of my $_ is experimental at inc/Module/Install/AutoInstall.pm - /usr/local/lib/perl5/site_perl/5.8.5/Module/Install/AutoInstall.pm line 35.
Use of my $_ is experimental at inc/Module/Install/AutoInstall.pm - /usr/local/lib/perl5/site_perl/5.8.5/Module/Install/AutoInstall.pm line 35.
Unknown regexp modifier "/n" at inc/Module/Install/AutoInstall.pm - /usr/local/lib/perl5/site_perl/5.8.5/Module/Install/AutoInstall.pm line 23, at end of line
Regexp modifiers "/a" and "/d" are mutually exclusive at inc/Module/Install/AutoInstall.pm - /usr/local/lib/perl5/site_perl/5.8.5/Module/Install/AutoInstall.pm line 23, at end of line
syntax error at inc/Module/Install/AutoInstall.pm - /usr/local/lib/perl5/site_perl/5.8.5/Module/Install/AutoInstall.pm line 23, near "m/--(?:default|skip|testonly)/and-t "
syntax error at inc/Module/Install/AutoInstall.pm - /usr/local/lib/perl5/site_perl/5.8.5/Module/Install/AutoInstall.pm line 29, near "}eval"
syntax error at inc/Module/Install/AutoInstall.pm - /usr/local/lib/perl5/site_perl/5.8.5/Module/Install/AutoInstall.pm line 32, near "}}"
  (Might be a runaway multi-line "" string starting on line 31)
Can't use global @_ in "my" at inc/Module/Install/AutoInstall.pm - /usr/local/lib/perl5/site_perl/5.8.5/Module/Install/AutoInstall.pm line 38, near "and @_ "
syntax error at inc/Module/Install/AutoInstall.pm - /usr/local/lib/perl5/site_perl/5.8.5/Module/Install/AutoInstall.pm line 53, near "}"
syntax error at inc/Module/Install/AutoInstall.pm - /usr/local/lib/perl5/site_perl/5.8.5/Module/Install/AutoInstall.pm line 59, near "}"
Compilation failed in require at inc/Module/Install.pm - /usr/local/lib/perl5/site_perl/5.8.5/Module/Install.pm line 267.
The 'auto_install' method does not exist in the 'inc' path!
Please remove the 'inc' directory and run Makefile.PL again to load it.
N/A
! Configure failed for PerlIO-via-symlink-0.05.
```

The offensive code is `(!defined($e)||$e!~m/--(?:default|skip|testonly)/and-t STDIN or` and it's been deprecated since 5.14 and will simply not work with 5.17 (and upcoming 5.18).

The affected distributions are marked as v=undef in https://gist.github.com/miyagawa/5457938

Because it's notorious Module::Install, the old version stays forever in inc/ until the author makes a new release with the updated version, i'm tempted to add a hack to kill auto_install by overwriting the files in inc/ with empty `sub auto_install {}`.
