### ISSUE TITLE
Doesn't work with cperl 5.22.2

### ISSUE THREAD

**Issue by dolmen** [miyagawa/cpanminus#500]
The minified cpanm doesn't work on cperl 5.22.2 (other releases not tested):
```
$ plenv install --as=5.22.2-cperl https://github.com/perl11/cperl/releases/download/cperl-5.22.2/cperl-5.22.2.tar.bz2
$ plenv shell 5.22.2-cperl
$ curl -L https://cpanmin.us | cperl - App::cpanminus
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   314    0   314    0     0    362      0 --:--:-- --:--:-- --:--:--   362
100  297k  100  297k    0     0   270k      0  0:00:01  0:00:01 --:--:--  270k
Missing $ on loop variable at - line 178.
Compilation failed in require at - line 28.
BEGIN failed--compilation aborted at - line 28.
Compilation failed in require at - line 32.
BEGIN failed--compilation aborted at - line 32.
Compilation failed in require at - line 499.
BEGIN failed--compilation aborted at - line 499.
```

Cc: @rurban
